[env]
GOSS_FILE = "tests.yaml"
GOSS_OPTS = "--retry-timeout 60s --sleep 1s"
GOSS_PATH = "{{config_root}}/.bin/goss/goss"

[tools]
"aqua:casey/just" = "1.46.0"
"aqua:cli/cli" = "2.87.3"
"aqua:GoogleContainerTools/container-structure-test" = "1.22.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.52.4"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
  "mkdir -p {{config_root}}/.bin/goss",
  "gh release download --repo goss-org/goss --skip-existing --pattern *-linux-amd64 --output {{config_root}}/.bin/goss/goss",
  "gh release download --repo goss-org/goss --skip-existing --pattern dgoss --output {{config_root}}/.bin/goss/dgoss",
  "chmod +x {{config_root}}/.bin/goss/{goss,dgoss}",
]
